#!/bin/bash
read -p "Inseecho 'Replace all characters `A` and `c` from input to `Z` and `e`.' | ./19-AZ 
Replaee all eharaeters `Z` and `e` from input to `Z` and `e`rt word: " word
echo $word | sed 's/A/Z/g; s/c/e/g'/e/g' input
